project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!/docs/scripts/*.qmd"
    - "!drafts.qmd"

website:
  title: "PS312 Statistical Research Methods"
  favicon: fav.png
  navbar:
    left:
      - text: " "
        href: index.qmd
    right:
      - icon: cloud-fill
        href: https://posit.cloud/

format:
  html:
    theme:
      light: [flatly, custom.scss]
    mainfont: roboto
    css: styles.css
    toc: true



